[build]
builder = "DOCKERFILE"
dockerfilePath = "../Dockerfile"

[deploy]
# Use the gunicorn config that handles PORT properly
startCommand = "cd /app && gunicorn --config gunicorn_config.py app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10